version: "2"

volumes:
  backend:

services:
  backend:
    network_mode: host
    #ports:
    #- "80:3000"
    build: .
    restart: always
    volumes:
      - "backend:/data"
    privileged: true
    depends_on:
      - db
  browser:
    network_mode: host
    image: balenablocks/browser
    depends_on:
      - backend
    restart: always
    privileged: true
  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "backend"
      MYSQL_USER: "backend"
      MYSQL_PASSWORD: "backend"

    network_mode: host
    volumes:
      - "backend:/db"
